basePath: /api/v1
definitions:
  main.User:
    properties:
      name:
        type: string
    type: object
host: localhost
info:
  contact: {}
  description: 这是测试文档
  license: {}
  title: das文档
  version: "1.0"
paths:
  /api/v1/tags:
    post:
      parameters:
      - description: name
        in: query
        name: name
        required: true
        type: string
      - description: State
        in: query
        name: state
        type: integer
      - description: CreatedBy
        in: body
        name: created_by
        required: true
        schema:
          $ref: '#/definitions/main.User'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 新增文章标签
swagger: "2.0"
